backend/api/sub-menu/config/routes.json
backend/api/sub-menu/controllers/sub-menu.js
backend/api/sub-menu/models/sub-menu.js
backend/api/sub-menu/models/sub-menu.settings.json
backend/api/sub-menu/services/sub-menu.js
backend/api/top-nav-item/config/routes.json
backend/api/top-nav-item/controllers/top-nav-item.js
backend/api/top-nav-item/models/top-nav-item.js
backend/api/top-nav-item/models/top-nav-item.settings.json
backend/api/top-nav-item/services/top-nav-item.js
backend/components/menu/dropdown.json
backend/components/menu/links.json
frontend/pages/index.js
frontend/styles/globals.css
frontend/yarn.lock

Reference for backend structuring: https://www.youtube.com/watch?v=cvL204xus1w

[NEW] Adds top navigation bar with menus to frontend and backend

---

frontend/pages/index.js
frontend/server.js

- Adds href for menu.link components in top nav bar.
- Creates proxy in frontend for `content-type-builder`

[Fix] Nav menu link, content-type-builder proxy

---

deploy/deploy.sh

this is all that is needed, as an example;  everybody configures nginx differently

Simplify deployment with nginx

---

README.md
cms/config/functions/bootstrap.js
cms/config/functions/fetchData.js

- Fix fetch data script for single types (release-notes, guides, top-nav-items)
- Adds env variable based triggering of fetch data script.

[FIX] Fetch data script for single types, env variable based trigerring

---

README.md

Signed-off-by: Debdut Chakraborty <debdut.chakraborty@rocket.chat>
Extra whitespaces are removed (side effect of ide), but main intention is to fix two typos (use rich diff).

Chore: Fix typos

---

app/components/menubar.js
app/components/rocketchatlinkbutton.js

Created a new RocketChatLinkButton Component which by default redirects to https://open.rocket.chat
https://user-images.githubusercontent.com/73601258/150687434-46c98142-5c44-4586-96eb-11d6c9870cf0.mp4

[NEW] RocketChatLinkButton Component

---

docs/components/README.md
docs/components/leaderboard/README.md

-  [x] I have read the Contributing Guide - https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat doc
-  [x] I have signed the CLA - https://cla-assistant.io/RocketChat/Rocket.Chat
-  [ ] I have added necessary documentation (if applicable)
Added documentation for Open-Source Leaderboard Component to make it easier for community builders to setup their own contribution leader board component and understand the flow of data from the cms to the component.
- **Note**  : The only warning being displayed on console now are due to the issues persisting in the react-slick library. [Reference](https://github.com/akiran/react-slick/issues/1195)
Fixes : #69 
Mentioned in the Issue

[NEW] Documentation for Open-Source Leaderboard Component

---

app/.env.local.sample
app/components/auth/rocketchat/README.md
app/components/auth/rocketchat/index.js
app/components/auth/rocketchat/styles/RocketChatAuthMenuButton.module.css
app/components/auth/rocketchat/styles/RocketChatAuthUI.module.css
app/components/auth/rocketchat/ui/RocketChatAuthMenuButton.js
app/components/auth/rocketchat/ui/RocketChatAuthUI.js
app/components/menubar.js
app/lib/auth/RocketChatOAuthProvider.js
app/package.json
app/pages/api/auth/[...nextauth].js
app/pages/api/auth/rocketchat-token-legacy.js

This PR will add RocketChat OAuth as the authentication provider for RC4Community.
The user data will be managed by Rocket.Chat server.

[NEW] RocketChat OAuth authentication for RC4Community

---

app/lib/github.js
cms/api/github-repositories/models/github-repositories.settings.json

-  [x] I have read the Contributing Guide - https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat doc
-  [x] I have signed the CLA - https://cla-assistant.io/RocketChat/Rocket.Chat
-  [x] I have added necessary documentation (if applicable)
Mentioned in the issue #103 
- Updated `github-repositories` schema to remove unnecessary and duplicate fields
- Fix undeclared variable  `GithubKitData()`  helper function

[Fix] Duplicate Column Error

---

app/components/mdpreview.js

-  [x] I have read the Contributing Guide - https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat doc
-  [x] I have signed the CLA - https://cla-assistant.io/RocketChat/Rocket.Chat
-  [x] I have added necessary documentation (if applicable)
Mentioned in the issue #105 
Re-Add Accidentally Deleted `MdPreview` Component

Re-Add MdPreview Component

---

app/pages/api/auth/rocketchat-token-legacy.js

Remove extra console.log in /api/auth/rocketchat-token-legacy.

[FIX] remove extra console.log in /api/auth/rocketchat-token-legacy

---

app/components/speakerinfotile.js
app/lib/dateTime.js
app/package-lock.json
app/package.json
app/pages/virtualconf/mainstage/index.js
app/styles/Mainstage.module.css
app/styles/SpeakerInfotiles.module.css
cms/api/speakers/models/speaker.settings.json
cms/config/functions/cron.js
cms/config/functions/fetchData.js
cms/config/functions/speaker.js
cms/config/initialData/speakers.json

-  [x] I have read the Contributing Guide - https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat doc
-  [x] I have signed the CLA - https://cla-assistant.io/RocketChat/Rocket.Chat
-  [x] I have added necessary documentation (if applicable)
Mentioned in the issue #101 
- Add `date_time` and 'duration_minutes' fields to speaker schema.
- Add `updateSpeakerData()` function to update the status of a particular speakers session depending on the time and date of the speaker session and its duration.
- Add `updateSpeakerData()` as cron job to update the speakers session state automatically every minute.
https://user-images.githubusercontent.com/70485812/160302042-e5a18606-f83f-472e-8f0e-0fe94adac218.mp4
- Add dateTime helper function in …

[NEW] New SpeakerInfotiles Component , Add Speakers Data , Update speaker Schema and auto-update live ,ended status fields of  speaker

---

app/components/inappchat/inappchat.js

Removes duplicate import of RocketChat.

Remove duplicate import

---

cms/config/initialData/speakers.json

also, fix some infos from speakers

[FIX] Add intro, networking and final notes slot to GSOC 2022 Summit Page

---

app/components/clientsideonly/videostreamer.js
app/pages/virtualconf/mainstage/[id].js
app/styles/Videostreamer.module.css

This PR fixes the video dimensions and the mini chat icon.
After the changes,
Thank you!

[IMPROVE][WIP] Change minor UI for mainstage

---

app/.env.local.sample
app/components/inappchat/inappchat.js
app/components/inappchat/inappchattextinput.js
app/components/inappchat/lib/api.js
app/pages/virtualconf/greenroom/index.js
app/pages/virtualconf/mainstage/[id].js

https://user-images.githubusercontent.com/73601258/161378343-19d68c09-077e-4078-b0d5-fa1c032f04a7.mp4

[IMPROVE] realtime emoji animation

---

cms/config/initialData/speakers.json

Description :
Update Speaker Data : Add Karan Bedi's Speaker Slot

[FIX] Add 14th Speaker

---

app/components/speakerinfotile.js

Fix final link infotile

---

app/pages/virtualconf/greenroom/index.js
app/pages/virtualconf/mainstage/[id].js

- changed host from community.liaison to open
- https://open.rocket.chat/channel/inappchat-test rid channel for testing

chore: changing from community.liaison to open

---

app/components/newscarousel.js
app/pages/index.js
app/styles/Newscarousel.module.css

Before : 
https://user-images.githubusercontent.com/53515714/163539776-b6353e24-a598-49af-b66e-c61c4362952f.mp4
After : 
https://user-images.githubusercontent.com/53515714/163539810-e4470a65-2207-4e96-a44a-030f07d863f4.mp4

[IMPROVE]  Added links and Hover Effect

---

app/components/layout.js
app/pages/virtualconf/mainstage/index.js

Removed Live text and link from the mainstage page and replaced it with a youtube link for the recordings.

[FIX] mainstage page 

---

README.md
cms/README.md
cms/config/server.js

This PR adds default `APP_KEYS` so it removes the need for setting up any other environment variables in `.env`, and the initial launch only requires running a few commands.
Thank you!

[IMPROVE] Strapi Setup OOB Experience

---

cms/config/initialData/carousels.json

I've added a minor bug fix,
- Fixed a link in the carousel to point to the correct url

[FIX] fixed an invalid url in the carousel

---

app/components/menubar.js

The PR removes the boolean check variable that decides which Auth to use between the Dummy Auth and RC Google-based OAuth.
Thank you!

[HFIX] Remove dummy auth bool condition

---

app/components/auth/rc-auth-google/gapi.js
app/components/hooks/useWindowSize.js
app/components/meetups/mainstage/Mainstage.js
app/components/meetups/mainstage/Toolbar.js
app/components/meetups/mainstage/VideoEmbedComponent.js
app/components/menubar/newMenuBar.js
app/components/rocketchatlinkbutton.js
app/middleware.js
app/package.json
app/pages/meetups/mainstage/index.js
app/styles/Menubar.module.css
app/styles/meetup.module.css

Closes #184
Create a "Watch YouTube and chat together" component for community builders to reuse in multiple routes of convenience. 
- Back-ported Mainstage component from [RC4Conferences](https://github.com/RocketChat/RC4Conferences/pull/35)
- Added a responsive embedded youtube video component
- Created a Mainstage component with embedded youtube video component and [EmbeddedChat](https://github.com/RocketChat/EmbeddedChat)
- Added a sample use case route at domain/meetups/mainstage with appropriate auth middleware for this particular route
- Replaced Dummy Auth in newMenuBar with existing RC4GoogleAuth component

[FEAT] Created a "Watch YouTube and chat Together" component

---

README.md
startBackend.sh
startdevenv.sh
superprofile/initFaunaOnce.sh
superprofile/log/initUser.fql
superprofile/log/initialize.sh
superprofile/log/schema.gql

Fixes the Superprofile Docker start script.
Adds:
Thank you!

[FIX] Missing a few startup script for Superprofile

---

app/components/newscarousel.js
app/styles/Newscarousel.module.css

Solved #205 
Before: 
After:
<a href="https://gitpod.io/#https://github.com/RocketChat/RC4Community/pull/209"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[Fixed] Responsiveness of Latest Community News Section
